### ISSUE TITLE
Multi-track support

### ISSUE THREAD

**Issue by gshipunov** [tlm-solutions/lofi#5]
Now that we have a lot of tracks, we need to support simultaneous gps tracks during correlation, and have a way to attribute track to specific run, e.g. what https://github.com/tlm-solutions/trekkie does already 

![image](https://user-images.githubusercontent.com/1297357/224468279-bfdecaac-f345-4400-93b8-3f79668f0395.png)

**Comment by tanneberger** [comment]
But this shouldn't be a problem because we save which gps points belong to which run

**Comment by gshipunov** [comment]
This was a problem for the standalone binary, which we yeeted
